### PR TITLE
Adding Spawn Point and more rooms

### PR DESCRIPTION
**Pull request by erickzanardo**
This PRs adds two things:

- Spawn point: Object on the tiled map with the `SPAWN_POINT` type
- More rooms and Objects to represent door gates

Door gates are objects on the tiled map, with the type: `ROOM_GATE`, it has three properties:
- `DESTINATION`: Name of the map that this gate leads to
- `DESTINATION_ROOM_ID`: Id (number) of the door on the destination where this gate leads to
- `GATE_ID`: The id (number) of this gate on this room.

@luanpotter will find this system very similar to what we have done on Tales of Lost Mine

### CODE REVIEW

**Comment by luanpotter** [comment]
is the "Name of the map" the file name? or is it within the json?

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by erickzanardo** [comment]
@luanpotter I thought on it been the filename, I think this way is simplistic enough, what are your thoughts?

**Comment by luanpotter** [comment]
that's perfect.

**Pull request merged**
